Forced ocs-live-dev and ocs-iso to use local image as base. More comments from review

diff --git a/sbin/ocs-live-dev b/sbin/ocs-live-dev
--- a/sbin/ocs-live-dev
+++ b/sbin/ocs-live-dev
@@ -426,53 +426,61 @@ if [ -z "$template_mode" ]; then
     # It's running from Clonezilla live media, use the existing resource
     template_mode="from-booting-live-media"
     [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-    echo "Found a Clonezilla live media... Will use that as a template..."
+    echo "Found a Clonewar live media... Will use that as a template..."
     [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
   else
-    template_mode="from-downloaded-live-media"
-    [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-    echo "No Clonezilla live media was found... Will use the downloaded template from Clonezilla repository..."
+    ##GDMS## JAYSON: Download option disabled for security
+    ##GDMS## OLD CODE
+    ##GDMS## template_mode="from-downloaded-live-media"
+    ##GDMS## [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+    ##GDMS## echo "No Clonezilla live media was found... Will use the downloaded template from Clonezilla repository..."
+    ##GDMS## [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+    ##GDMS## NEW CODE
+    [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+    echo "Clonewar live media not found. Download option disabled. Please run from an existing Clonewar bootable."
+    read
     [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+    exit 1
   fi 
 fi 
-
-if [ "$template_mode" = "from-downloaded-live-media" ]; then
-  if [ ! -f "$DEBIAN_ISO" ]; then
-    echo "Searching for the latest Clonezilla live iso..."
-    cz_ver="$(LC_ALL=C get-latest-ocs-live-ver $clonezilla_iso_branch)"
-    clonezilla_iso_fname="clonezilla-live-${cz_ver}${clonezilla_iso_arch_tag}.iso"
-    iso_url_for_pxe_ocs_live="http://downloads.sourceforge.net/clonezilla/$clonezilla_iso_fname"
-    echo "We need Clonnezilla live iso to create such a recovery cd."
-    echo "Downloadling the iso file from $iso_url_for_pxe_ocs_live..."
-    wget $iso_url_for_pxe_ocs_live
-    get_iso_rc=$?
-    # validate it
-    if [ "$get_iso_rc" -eq 0 ]; then
-      echo -n "Validating $clonezilla_iso_fname... "
-      md5_tmp="$(mktemp -d /tmp/isomd5.XXXXXX)"
-      #  wget http://free.nchc.org.tw/clonezilla-live/stable/MD5SUMS
-      echo -n "Downloading $md5_file_url... "
-      wget $wget_opt -P "$md5_tmp" $md5_file_url
-      if ! grep -w "$clonezilla_iso_fname" $md5_tmp/$md5_file | md5sum -c; then
-        [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
-        echo "$DEBIAN_ISO is broken! Try to remove $clonezilla_iso_fname and run this program again."
-        [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-        echo "$msg_program_stop"
-        exit 1
-      fi
-      # Rename it to the template iso file name (fixed name)
-      mv -f $clonezilla_iso_fname $DEBIAN_ISO
-    else
-      [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
-      echo "Unable to download $iso_url_for_pxe_ocs_live!"
-      [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-      echo "$msg_program_stop"
-      exit 1
-    fi
-  else
-    echo "A template iso ($DEBIAN_ISO) was found!"
-  fi
-fi
+##GDMS## BLOCK REMOVED FOR SECURITY
+##GDMS## if [ "$template_mode" = "from-downloaded-live-media" ]; then
+##GDMS##  if [ ! -f "$DEBIAN_ISO" ]; then
+##GDMS##    echo "Searching for the latest Clonezilla live iso..."
+##GDMS##    cz_ver="$(LC_ALL=C get-latest-ocs-live-ver $clonezilla_iso_branch)"
+##GDMS##    clonezilla_iso_fname="clonezilla-live-${cz_ver}${clonezilla_iso_arch_tag}.iso"
+##GDMS##    iso_url_for_pxe_ocs_live="http://downloads.sourceforge.net/clonezilla/$clonezilla_iso_fname"
+##GDMS##    echo "We need Clonnezilla live iso to create such a recovery cd."
+##GDMS##    echo "Downloadling the iso file from $iso_url_for_pxe_ocs_live..."
+##GDMS##    wget $iso_url_for_pxe_ocs_live
+##GDMS##    get_iso_rc=$?
+##GDMS##    # validate it
+##GDMS##    if [ "$get_iso_rc" -eq 0 ]; then
+##GDMS##      echo -n "Validating $clonezilla_iso_fname... "
+##GDMS##      md5_tmp="$(mktemp -d /tmp/isomd5.XXXXXX)"
+##GDMS##      #  wget http://free.nchc.org.tw/clonezilla-live/stable/MD5SUMS
+##GDMS##      echo -n "Downloading $md5_file_url... "
+##GDMS##      wget $wget_opt -P "$md5_tmp" $md5_file_url
+##GDMS##      if ! grep -w "$clonezilla_iso_fname" $md5_tmp/$md5_file | md5sum -c; then
+##GDMS##        [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+##GDMS##        echo "$DEBIAN_ISO is broken! Try to remove $clonezilla_iso_fname and run this program again."
+##GDMS##        [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+##GDMS##        echo "$msg_program_stop"
+##GDMS##        exit 1
+##GDMS##      fi
+##GDMS##      # Rename it to the template iso file name (fixed name)
+##GDMS##      mv -f $clonezilla_iso_fname $DEBIAN_ISO
+##GDMS##    else
+##GDMS##      [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+##GDMS##      echo "Unable to download $iso_url_for_pxe_ocs_live!"
+##GDMS##      [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+##GDMS##      echo "$msg_program_stop"
+##GDMS##      exit 1
+##GDMS##    fi
+##GDMS##  else
+##GDMS##    echo "A template iso ($DEBIAN_ISO) was found!"
+##GDMS##  fi
+##GDMS## fi
 
 if [ "$insert_mode" = "prog_and_img" ]; then
   # 2 cases:
